### ISSUE TITLE
CHAT

### ISSUE THREAD

**Issue by Israel-Laguan** [Israel-Laguan/coolticket-server#11]
Es un placer informarte que avanzas a la siguiente etapa! Esta etapa definirá todo, así que te animamos a poner mucho esfuerzo.

El siguiente reto consiste en probar tu personalidad, profesionalismo y trabajo en equipo. Para ello queremos que trabajes con un equipo de otros programadores en un ambiente cercano al que se espera trabajes en el futuro.

Paso 1: Solicita permiso para hacer commits a este repositorio al correo israellaguan@gmail.com:

https://github.com/Israel-Laguan/coolticket-server

Paso 2: Preséntate en el issue #11 con un comentario y conoce a tus compañeros.

Paso 3:  Tomate tu tiempo para leer los tíquets o Issues en el repositorio, así como a leer el código. Notaras que hay tareas sencillas pero también mas complicadas. Se espera que leas desde ahora hasta el Lunes 26.

Paso 4: El domingo 25 de Octubre se procederá a evaluar en una escala numérica la dificultad de cada tíquet. Cada tíquet puede tener entre 0 (demasiado fácil) hasta 6 (Muy difícil, necesita dividirse). La discusión se hará en el chat, y el resultado sera puesto en cada Issue en el repositorio.

Paso 5: Como equipo se hablara que tíquets tomaran cada quien en el chat el Lunes 26 de Octubre del presente. Se espera que cada uno tome tantos como quiera o pueda, hablando primero en el chat, y luego asignandose el issue en el repositorio. Se espera que sea una platica civilizada y profesional.

Paso 6: Cada developer puede empezar sus tíquets inmediatamente, subiendo el código respetando la metodología conocida como "gitflow", es  decir en una nueva rama que empieza en "feature/" mas un indicador, que parte de la rama "dev". Al terminar el trabajo y "solucionar" el issue, se hará un Pull Request (PR) a "dev", que será verificado por mí.

Paso 7: Todos los developers pueden (y se espera) que hagan comentarios o Peer Review sobre todos los PRs. Cada developer incluirá como reviewers a los demás en su equipo y a mí. El objetivo acá es que los demás identifiquen puntos a mejorar, mejoras al estilo, preguntas, etc.

Paso 7: Cada developer es responsable de solucionar todos los comentarios hechos en el issue sobre problemas con su trabajo sobre el issue, si los hubiera. Se entiende que todo esta bien y ha solucionado su issue si hay un Merge.

Paso 8: Se extenderá la prueba por una semana laboral, es decir que la ultima oportunidad para hacer un commit es el Viernes 30 de Octubre. 

Los resultados de la prueba deben proporcionarse por mensaje personal usando Messenger. Se espera que el Sábado 31 cada quien tenga sus respuestas para empezar el Lunes 2.

**Comment by martycabj1999** [comment]
Hola buenas me presento, soy Martin Tito de Argentina tengo 21 años y soy developer Full Stack.
Cualquier cosa que necesiten para resolver algun ticket me ofrezco sin problema.

**Comment by Israel-Laguan** [comment]
> Hola buenas me presento, soy Martin Tito de Argentina tengo 21 años y soy developer Full Stack.
> Cualquier cosa que necesiten para resolver algun ticket me ofrezco sin problema.

Hola que tal Martín! Mucho gusto!

**Comment by Israel-Laguan** [comment]
Soy Israel Laguan, el creador y mantainer de este repositorio,  mucho gusto!

**Comment by manuelbol98** [comment]
buenas tardes mi nombre es manuel alejandro bolaños , edad 22 años , soy tecnologo de sistema 
preparado para aprender mas :V

**Comment by albriveratorres** [comment]
Hola que tal, Soy Eddy Rivera De Chihuahua México, soy Ingeniero en Tecnologías y ya tengo un poco de experiencia como desarrollador pero me sigo preparando mas en este campo. un saludo a todos

**Comment by manuelbol98** [comment]
mucho gente , queria preguntar si ya descargaron el archivo o todavia no se tiene que descargar ?

**Comment by Israel-Laguan** [comment]
Pueden descargar el repositorio desde ya, no hay problema

**Comment by manuelbol98** [comment]
listo muchas gracias , gente dare mi cien por cien con actitud positiva siempre

**Comment by Israel-Laguan** [comment]
Hoy es el ultimo día para revisar el código y las issues. Desde hoy o mañana pueden ir dejando su valoración en una escala del 0 hasta el 6. SI Se deciden por un 6 por favor comentar por que y propongan como sera la división. Muchas gracias.

**Comment by albriveratorres** [comment]
Tengo un problema, no se si ya alguno de ustedes ya pudo correr el proyecto, pero cuando corro en consola el `docker-compose up` me aparece esto, luego ya se creo la base de datos y se migraron los datos con `set-db:dev`, tengo la carpeta de node_modules, no me aparece nada en el navegador alguna idea que esta pasando??

api_1  |         SERVER v0.5.0 
api_1  | Server for tickets system!
api_1  |          
api_1  | 2020-10-25 20:11 [INFO]:       App listening on http://localhost:8383/ping
api_1  | 2020-10-25 20:11 [INFO]:       port 8383 (HTTP)
api_1  | 2020-10-25 20:11 [INFO]:       port 8080 (HTTP) 

cuando agrego otra consola y agregro `npm run dev` aparece

coolticket-server@0.5.0 dev: `NODE_ENV=development nodemon -r dotenv/config index.js`

lo intente hacer con el comando npm run start pero tampoco aparece nada, necesito ayuda

**Comment by Israel-Laguan** [comment]
Y tenes las credenciales para la base de datos?

**Comment by Israel-Laguan** [comment]
Muchachos, les recuerdo que mañana pueden empezar a asignarse tareas.

**Comment by martycabj1999** [comment]
@Israel-Laguan disculpa lamento tener que decirte que me voy a tener que bajar, porque hoy me robaron la computadora en argentina y voy a estar aproximadamente 1 o 2 semanas hasta que compre alguna.

Pido disculpas y gracias por la oportunidad igual.

**Comment by albriveratorres** [comment]
ya revise las credenciales en el .env y parecen estar correctas, pero seguiré buscando en caso de tener algo incorrecto

**Comment by Israel-Laguan** [comment]
> @Israel-Laguan disculpa lamento tener que decirte que me voy a tener que bajar.

Te escribo al privado.

**Comment by Israel-Laguan** [comment]
> Tengo un problema, no se si ya alguno de ustedes ya pudo correr el proyecto, pero cuando corro en consola el `docker-compose up` me aparece esto, luego ya se creo la base de datos y se migraron los datos con `set-db:dev`, tengo la carpeta de node_modules, no me aparece nada en el navegador alguna idea que esta pasando??
> 
> api_1 | SERVER v0.5.0
> api_1 | Server for tickets system!
> api_1 |
> api_1 | 2020-10-25 20:11 [INFO]: App listening on http://localhost:8383/ping
> api_1 | 2020-10-25 20:11 [INFO]: port 8383 (HTTP)
> api_1 | 2020-10-25 20:11 [INFO]: port 8080 (HTTP)
> 
> cuando agrego otra consola y agregro `npm run dev` aparece
> 
> coolticket-server@0.5.0 dev: `NODE_ENV=development nodemon -r dotenv/config index.js`
> 
> lo intente hacer con el comando npm run start pero tampoco aparece nada, necesito ayuda

El siguiente paso es abrir en un navegador la dirección que sale ahí en la consola

**Comment by Israel-Laguan** [comment]
Por cualquier cosa nota que es un proyecto de nodejs, no de react por lo que no abre un frontend sino un endpoint

**Comment by Israel-Laguan** [comment]
> ya revise las credenciales en el .env y parecen estar correctas, pero seguiré buscando en caso de tener algo incorrecto

Puedes describir mejor tu problema? Recuerda que puedes incluir imágenes o gifs (incluso links a videos) para explicar mejor. En última instancia graba un video y lo compartes por Messenger

**Comment by albriveratorres** [comment]
Siento como que me falta mostrar la documentacion del server de swaggerUI, no la puedo ver en el navegador, de toda maneras hice un video  te lo mando po messenger, ya tengo un buen rato trabado ahi

**Comment by Israel-Laguan** [comment]
Con @albriveratorres hicimos unas pruebas en el código, y los cambios necesarios para correr el proyecto con nodejs están en los nuevos commits. Así que por favor:
- Usen la rama `dev`, es decir `git checkout dev`
- Bajen lo ultimo, es decir `git fetch -a && git pull --rebase`

**Comment by Israel-Laguan** [comment]
Les pasare las credenciales de heroku en formato env por Messenger

**Comment by albriveratorres** [comment]
Que tal, estaba por empezar a crear el front-end y me tope con 1 problema y le empecé a buscar solución, hasta donde yo veo y corríjanme si me equivoco, va los pasos que hice:

1.- quise implementar con npm create-react-app nombre-de-app, dentro de la carpeta de /coolticket-server, pero esto causa error debido a que ya existe una carpeta en esta carpeta (/coolticket-server), no puedo crear un proyecto de react dentro del server.

2.- con Webpack  se puede crear un proyecto de react y administrarlo con babel, pero el problema es que no hay un archivo el cual lo mande para pandarlo llamar ejemplo desde un html mandar llamar el bandle.js de react. y todos sus archivos generados, 
entcs aqui estoy un poco atorado y decidi hacer el paso 3.

3.- decidi borrar lo del paso 2 que es muy sencillo de volver a realizar e hice un front-end fuera de la carpeta de /coolticket-server, pero no me percate de como subir esa parte, ya que quedaría los directorios estarían en la misma carpeta y no e una subcarpeta de /coolticket-server.

yo creo que tendría que regresar a seguir haciéndolo con el paso 2 pero me falta el archivo para mandar llamar el .js de react

**Comment by Israel-Laguan** [comment]
Hola @albriveratorres , te comento:

1.- CRA este proyecto es del lado del servidor. Hay dos formas de meterle react: hacer una carpeta adentro de `public/`, o hacer un repositorio aparte, servirlo en un servidor aparte, y conectarlos por el API. En este caso creo que lo mejor es ponerlo adentro de `public/` usando webpack o parcel, en el siguiente punt lo vemos.
2.- La solución es modificar adonde toma y adonde deposita el resultado webpack/parcel. Recuerda que puedes modificar eso sin problemas en la configuración.
3.- Debe ir adentro de la carpeta del repositorio. Si usamos webpack o parcel propongo que el origen este en la carpeta a crear `frontend/` y se deposite en la carpeta `public/`.

Por otro lado este trabajo ya estaba contemplado en el issue #9

**Comment by Israel-Laguan** [comment]
Aún otra posibilidad es crear un tiquete solo para eso. Que opinan?

**Comment by albriveratorres** [comment]
dentro de la carptea public tendria un archivo index.html que este tenga un script <script src="bundle.js"></script> para mandar llamar el proyecto de react, seria una solucion sencilla

**Comment by Israel-Laguan** [comment]
> dentro de la carptea public tendria un archivo index.html que este tenga un script <script src="bundle.js"></script> para mandar llamar el proyecto de react, seria una solucion sencilla

Si, exacto.

**Comment by albriveratorres** [comment]
lo pruebo, tengo una conexión inestable en estos momentos, no estoy en casa

**Comment by albriveratorres** [comment]
ya lo agregue, solo en que puerto me va a mostrar el frontend de public o que ruta ya que la api me la esta mostrando en el 8383

**Comment by Israel-Laguan** [comment]
Para el frontend en desarrollo puedes seguir usando "3000", y el server que quede en "8383". En el caso del script en el package podría ser "npm run dev:front", que te parece?

**Comment by albriveratorres** [comment]
ok, me parece, asi no se tiene conflicto con el npm run dev con el el dotenv

**Comment by Israel-Laguan** [comment]
Buenos días, recordarles que hoy es el último día para subir los PR. También que si alguien sube los demás deben hacer pair review.

**Comment by albriveratorres** [comment]
me quede un poco atascado con webpack y todas sus configuraciones, desidi irme por la otra opcion hice una carpeta dentro de la carpeta coolticket-server, con el mismo nombre y empezar agregar react, dentro de la carpeta original hice un CRA con en nombre de coolticket-frontend y esta funcionando pero no creo terminar son muchas las rutas y los componentes

**Comment by Israel-Laguan** [comment]
@albriveratorres en el issue #9 solo menciona 2 rutas, o a cuales otras te refieres?

**Comment by albriveratorres** [comment]
Estaba pensando hacer una para crear usuarios,  login, crear tickets, lo veo de esa manera, iba a realizar la parte de los usuarios,  la ruta de logón y crear usuarios lo iba a hacer en rutas separadas para que no estuvieran en una misma, a lo que me refiero es toda las funciones no creo acabarlas

**Comment by Israel-Laguan** [comment]
@albriveratorres si vas a crear algo arriba mencione que debes crear nuevas issues. De lo contrario estarías pasando encima del mantainer del repositorio. Recuerda que en una empresa a uno le toca seguir lo que el cliente o los mánagers han planteado. Esta buena la iniciativa pero a veces toca como hacer paso a paso.

**Comment by albriveratorres** [comment]
ok, no hay problema, puedo regresar al commit anterior sin problema, le puse nombre para identificarlo en caso de algun problema, llevo varios y el codigo casi puedo hacer un copy paste despues de generar los archivos o copiarlos a mi pc y luego copiarlos al front

**Comment by albriveratorres** [comment]
lo regreso?? pero como le hacemos

**Comment by Israel-Laguan** [comment]
Lo otro que hagas los issues con cada cosa que hiciste

**Comment by albriveratorres** [comment]
ok

**Comment by Israel-Laguan** [comment]
Hoy es el día en que revisaba los últimos commits pero no hay ninguno 😆 . El proceso queda terminado. Muchas gracias por participar.
